### ISSUE TITLE
Will it work in the future on arch linux?

### ISSUE THREAD

**Issue by bambirombi** [shaunabanana/intrigue#2]
I would be interesting on running this software with linux. Do you have any plans for it or only for mac?

**Comment by shaunabanana** [comment]
Hi! Thank you for asking!

As Intrigue is developed using Electron, it should work on all platforms. However, I don't have a linux machine / VM to test it on for now. When I find time, I could try installing a linux VM to build a binary. But in the meantime, if it is possible, you're welcome to try building it yourself :)

It should be as simple as installing Node.js, cloning this repository and running the following:
```
npm install
npm run electron:build
```
Please let me know how it goes if you try to build it!

**Comment by shaunabanana** [comment]
Update: I've published a linux binary, built using WSL on a PC. Please let me know if there's any problem :)

**Comment by bambirombi** [comment]
Thanks! It works on arch.
